### ISSUE TITLE
Can't build on Windows 7 with Python 2.7.9

### ISSUE THREAD

**Issue by Simon-Davies** [FSecureLABS/drozer#323]
### Steps to reproduce
1. Run the command:

py -2 setup.py bdist_msi

### Expected behaviour

Should successfully build the msi to install

### Actual behaviour

Console output:
copying build\lib\drozer\modules\shell\startexec.py -> build\bdist.win-amd64\msi
\Lib\site-packages\drozer\modules\shell
copying build\lib\drozer\modules\shell\__init__.py -> build\bdist.win-amd64\msi\
Lib\site-packages\drozer\modules\shell
creating build\bdist.win-amd64\msi\Lib\site-packages\drozer\modules\tools
copying build\lib\drozer\modules\tools\file.py -> build\bdist.win-amd64\msi\Lib\
site-packages\drozer\modules\tools
creating build\bdist.win-amd64\msi\Lib\site-packages\drozer\modules\tools\setup
creating build\bdist.win-amd64\msi\Lib\site-packages\drozer\modules\tools\setup\
arm
creating build\bdist.win-amd64\msi\Lib\site-packages\drozer\modules\tools\setup\
arm\nopie
copying build\lib\drozer\modules\tools\setup\arm\nopie\busybox -> build\bdist.wi
n-amd64\msi\Lib\site-packages\drozer\modules\tools\setup\arm\nopie
copying build\lib\drozer\modules\tools\setup\arm\nopie\__init__.py -> build\bdis
t.win-amd64\msi\Lib\site-packages\drozer\modules\tools\setup\arm\nopie
creating build\bdist.win-amd64\msi\Lib\site-packages\drozer\modules\tools\setup\
arm\pie
copying build\lib\drozer\modules\tools\setup\arm\pie\busybox -> build\bdist.win-
amd64\msi\Lib\site-packages\drozer\modules\tools\setup\arm\pie
copying build\lib\drozer\modules\tools\setup\arm\pie\__init__.py -> build\bdist.
win-amd64\msi\Lib\site-packages\drozer\modules\tools\setup\arm\pie
copying build\lib\drozer\modules\tools\setup\arm\__init__.py -> build\bdist.win-
amd64\msi\Lib\site-packages\drozer\modules\tools\setup\arm
copying build\lib\drozer\modules\tools\setup\busybox.py -> build\bdist.win-amd64
\msi\Lib\site-packages\drozer\modules\tools\setup
creating build\bdist.win-amd64\msi\Lib\site-packages\drozer\modules\tools\setup\
minimal-su
creating build\bdist.win-amd64\msi\Lib\site-packages\drozer\modules\tools\setup\
minimal-su\jni
copying build\lib\drozer\modules\tools\setup\minimal-su\jni\Android.mk -> build\
bdist.win-amd64\msi\Lib\site-packages\drozer\modules\tools\setup\minimal-su\jni
copying build\lib\drozer\modules\tools\setup\minimal-su\jni\su.c -> build\bdist.
win-amd64\msi\Lib\site-packages\drozer\modules\tools\setup\minimal-su\jni
creating build\bdist.win-amd64\msi\Lib\site-packages\drozer\modules\tools\setup\
minimal-su\libs
creating build\bdist.win-amd64\msi\Lib\site-packages\drozer\modules\tools\setup\
minimal-su\libs\armeabi
copying build\lib\drozer\modules\tools\setup\minimal-su\libs\armeabi\su -> build
\bdist.win-amd64\msi\Lib\site-packages\drozer\modules\tools\setup\minimal-su\lib
s\armeabi
copying build\lib\drozer\modules\tools\setup\minimal-su\libs\armeabi\__init__.py
 -> build\bdist.win-amd64\msi\Lib\site-packages\drozer\modules\tools\setup\minim
al-su\libs\armeabi
copying build\lib\drozer\modules\tools\setup\minimal-su\libs\__init__.py -> buil
d\bdist.win-amd64\msi\Lib\site-packages\drozer\modules\tools\setup\minimal-su\li
bs
copying build\lib\drozer\modules\tools\setup\minimal-su\__init__.py -> build\bdi
st.win-amd64\msi\Lib\site-packages\drozer\modules\tools\setup\minimal-su
copying build\lib\drozer\modules\tools\setup\su.py -> build\bdist.win-amd64\msi\
Lib\site-packages\drozer\modules\tools\setup
creating build\bdist.win-amd64\msi\Lib\site-packages\drozer\modules\tools\setup\
x86
copying build\lib\drozer\modules\tools\setup\x86\busybox -> build\bdist.win-amd6
4\msi\Lib\site-packages\drozer\modules\tools\setup\x86
copying build\lib\drozer\modules\tools\setup\x86\__init__.py -> build\bdist.win-
amd64\msi\Lib\site-packages\drozer\modules\tools\setup\x86
copying build\lib\drozer\modules\tools\setup\__init__.py -> build\bdist.win-amd6
4\msi\Lib\site-packages\drozer\modules\tools\setup
copying build\lib\drozer\modules\tools\__init__.py -> build\bdist.win-amd64\msi\
Lib\site-packages\drozer\modules\tools
copying build\lib\drozer\modules\__init__.py -> build\bdist.win-amd64\msi\Lib\si
te-packages\drozer\modules
creating build\bdist.win-amd64\msi\Lib\site-packages\drozer\payload
copying build\lib\drozer\payload\builder.py -> build\bdist.win-amd64\msi\Lib\sit
e-packages\drozer\payload
copying build\lib\drozer\payload\manager.py -> build\bdist.win-amd64\msi\Lib\sit
e-packages\drozer\payload
copying build\lib\drozer\payload\__init__.py -> build\bdist.win-amd64\msi\Lib\si
te-packages\drozer\payload
creating build\bdist.win-amd64\msi\Lib\site-packages\drozer\repoman
copying build\lib\drozer\repoman\installer.py -> build\bdist.win-amd64\msi\Lib\s
ite-packages\drozer\repoman
copying build\lib\drozer\repoman\manager.py -> build\bdist.win-amd64\msi\Lib\sit
e-packages\drozer\repoman
copying build\lib\drozer\repoman\remotes.py -> build\bdist.win-amd64\msi\Lib\sit
e-packages\drozer\repoman
copying build\lib\drozer\repoman\repositories.py -> build\bdist.win-amd64\msi\Li
b\site-packages\drozer\repoman
copying build\lib\drozer\repoman\repository_builder.py -> build\bdist.win-amd64\
msi\Lib\site-packages\drozer\repoman
copying build\lib\drozer\repoman\__init__.py -> build\bdist.win-amd64\msi\Lib\si
te-packages\drozer\repoman
creating build\bdist.win-amd64\msi\Lib\site-packages\drozer\server
copying build\lib\drozer\server\dz.py -> build\bdist.win-amd64\msi\Lib\site-pack
ages\drozer\server
copying build\lib\drozer\server\files.py -> build\bdist.win-amd64\msi\Lib\site-p
ackages\drozer\server
copying build\lib\drozer\server\heartbeat.py -> build\bdist.win-amd64\msi\Lib\si
te-packages\drozer\server
creating build\bdist.win-amd64\msi\Lib\site-packages\drozer\server\protocols
copying build\lib\drozer\server\protocols\byte_stream.py -> build\bdist.win-amd6
4\msi\Lib\site-packages\drozer\server\protocols
copying build\lib\drozer\server\protocols\drozerp.py -> build\bdist.win-amd64\ms
i\Lib\site-packages\drozer\server\protocols
copying build\lib\drozer\server\protocols\http.py -> build\bdist.win-amd64\msi\L
ib\site-packages\drozer\server\protocols
copying build\lib\drozer\server\protocols\shell.py -> build\bdist.win-amd64\msi\
Lib\site-packages\drozer\server\protocols
copying build\lib\drozer\server\protocols\__init__.py -> build\bdist.win-amd64\m
si\Lib\site-packages\drozer\server\protocols
creating build\bdist.win-amd64\msi\Lib\site-packages\drozer\server\receivers
copying build\lib\drozer\server\receivers\frame.py -> build\bdist.win-amd64\msi\
Lib\site-packages\drozer\server\receivers
copying build\lib\drozer\server\receivers\http.py -> build\bdist.win-amd64\msi\L
ib\site-packages\drozer\server\receivers
copying build\lib\drozer\server\receivers\__init__.py -> build\bdist.win-amd64\m
si\Lib\site-packages\drozer\server\receivers
copying build\lib\drozer\server\server.py -> build\bdist.win-amd64\msi\Lib\site-
packages\drozer\server
copying build\lib\drozer\server\uploader.py -> build\bdist.win-amd64\msi\Lib\sit
e-packages\drozer\server
creating build\bdist.win-amd64\msi\Lib\site-packages\drozer\server\web_root
copying build\lib\drozer\server\web_root\drozer.png -> build\bdist.win-amd64\msi
\Lib\site-packages\drozer\server\web_root
copying build\lib\drozer\server\web_root\favicon.png -> build\bdist.win-amd64\ms
i\Lib\site-packages\drozer\server\web_root
copying build\lib\drozer\server\web_root\index.html -> build\bdist.win-amd64\msi
\Lib\site-packages\drozer\server\web_root
copying build\lib\drozer\server\web_root\jquery.js -> build\bdist.win-amd64\msi\
Lib\site-packages\drozer\server\web_root
copying build\lib\drozer\server\web_root\labs.png -> build\bdist.win-amd64\msi\L
ib\site-packages\drozer\server\web_root
copying build\lib\drozer\server\__init__.py -> build\bdist.win-amd64\msi\Lib\sit
e-packages\drozer\server
copying build\lib\drozer\session.py -> build\bdist.win-amd64\msi\Lib\site-packag
es\drozer
creating build\bdist.win-amd64\msi\Lib\site-packages\drozer\ssl
copying build\lib\drozer\ssl\bcprov-ext-jdk15on-1.46.jar -> build\bdist.win-amd6
4\msi\Lib\site-packages\drozer\ssl
copying build\lib\drozer\ssl\ca.py -> build\bdist.win-amd64\msi\Lib\site-package
s\drozer\ssl
creating build\bdist.win-amd64\msi\Lib\site-packages\drozer\ssl\embedded_ca
copying build\lib\drozer\ssl\embedded_ca\drozer-ca.bks -> build\bdist.win-amd64\
msi\Lib\site-packages\drozer\ssl\embedded_ca
copying build\lib\drozer\ssl\embedded_ca\drozer-ca.crt -> build\bdist.win-amd64\
msi\Lib\site-packages\drozer\ssl\embedded_ca
copying build\lib\drozer\ssl\embedded_ca\drozer-ca.jks -> build\bdist.win-amd64\
msi\Lib\site-packages\drozer\ssl\embedded_ca
copying build\lib\drozer\ssl\embedded_ca\drozer-ca.key -> build\bdist.win-amd64\
msi\Lib\site-packages\drozer\ssl\embedded_ca
copying build\lib\drozer\ssl\embedded_ca\drozer-server.crt -> build\bdist.win-am
d64\msi\Lib\site-packages\drozer\ssl\embedded_ca
copying build\lib\drozer\ssl\embedded_ca\drozer-server.key -> build\bdist.win-am
d64\msi\Lib\site-packages\drozer\ssl\embedded_ca
copying build\lib\drozer\ssl\embedded_ca\__init__.py -> build\bdist.win-amd64\ms
i\Lib\site-packages\drozer\ssl\embedded_ca
copying build\lib\drozer\ssl\provider.py -> build\bdist.win-amd64\msi\Lib\site-p
ackages\drozer\ssl
copying build\lib\drozer\ssl\ssl_manager.py -> build\bdist.win-amd64\msi\Lib\sit
e-packages\drozer\ssl
copying build\lib\drozer\ssl\__init__.py -> build\bdist.win-amd64\msi\Lib\site-p
ackages\drozer\ssl
copying build\lib\drozer\util.py -> build\bdist.win-amd64\msi\Lib\site-packages\
drozer
copying build\lib\drozer\__init__.py -> build\bdist.win-amd64\msi\Lib\site-packa
ges\drozer
creating build\bdist.win-amd64\msi\Lib\site-packages\mwr
creating build\bdist.win-amd64\msi\Lib\site-packages\mwr\common
copying build\lib\mwr\common\argparse_completer.py -> build\bdist.win-amd64\msi\
Lib\site-packages\mwr\common
copying build\lib\mwr\common\cli.py -> build\bdist.win-amd64\msi\Lib\site-packag
es\mwr\common
copying build\lib\mwr\common\cmd_ext.py -> build\bdist.win-amd64\msi\Lib\site-pa
ckages\mwr\common
copying build\lib\mwr\common\command_wrapper.py -> build\bdist.win-amd64\msi\Lib
\site-packages\mwr\common
copying build\lib\mwr\common\console.py -> build\bdist.win-amd64\msi\Lib\site-pa
ckages\mwr\common
copying build\lib\mwr\common\fs.py -> build\bdist.win-amd64\msi\Lib\site-package
s\mwr\common
copying build\lib\mwr\common\list.py -> build\bdist.win-amd64\msi\Lib\site-packa
ges\mwr\common
copying build\lib\mwr\common\logger.py -> build\bdist.win-amd64\msi\Lib\site-pac
kages\mwr\common
copying build\lib\mwr\common\path_completion.py -> build\bdist.win-amd64\msi\Lib
\site-packages\mwr\common
copying build\lib\mwr\common\stream.py -> build\bdist.win-amd64\msi\Lib\site-pac
kages\mwr\common
copying build\lib\mwr\common\system.py -> build\bdist.win-amd64\msi\Lib\site-pac
kages\mwr\common
copying build\lib\mwr\common\text.py -> build\bdist.win-amd64\msi\Lib\site-packa
ges\mwr\common
creating build\bdist.win-amd64\msi\Lib\site-packages\mwr\common\twisted
copying build\lib\mwr\common\twisted\stream_receiver.py -> build\bdist.win-amd64
\msi\Lib\site-packages\mwr\common\twisted
copying build\lib\mwr\common\twisted\__init__.py -> build\bdist.win-amd64\msi\Li
b\site-packages\mwr\common\twisted
copying build\lib\mwr\common\__init__.py -> build\bdist.win-amd64\msi\Lib\site-p
ackages\mwr\common
copying build\lib\mwr\__init__.py -> build\bdist.win-amd64\msi\Lib\site-packages
\mwr
creating build\bdist.win-amd64\msi\Lib\site-packages\pydiesel
creating build\bdist.win-amd64\msi\Lib\site-packages\pydiesel\api
creating build\bdist.win-amd64\msi\Lib\site-packages\pydiesel\api\builders
copying build\lib\pydiesel\api\builders\reflection_request.py -> build\bdist.win
-amd64\msi\Lib\site-packages\pydiesel\api\builders
copying build\lib\pydiesel\api\builders\reflection_response.py -> build\bdist.wi
n-amd64\msi\Lib\site-packages\pydiesel\api\builders
copying build\lib\pydiesel\api\builders\system_request.py -> build\bdist.win-amd
64\msi\Lib\site-packages\pydiesel\api\builders
copying build\lib\pydiesel\api\builders\system_response.py -> build\bdist.win-am
d64\msi\Lib\site-packages\pydiesel\api\builders
copying build\lib\pydiesel\api\builders\__init__.py -> build\bdist.win-amd64\msi
\Lib\site-packages\pydiesel\api\builders
copying build\lib\pydiesel\api\exceptions.py -> build\bdist.win-amd64\msi\Lib\si
te-packages\pydiesel\api
copying build\lib\pydiesel\api\frame.py -> build\bdist.win-amd64\msi\Lib\site-pa
ckages\pydiesel\api
creating build\bdist.win-amd64\msi\Lib\site-packages\pydiesel\api\handlers
copying build\lib\pydiesel\api\handlers\system_request_handler.py -> build\bdist
.win-amd64\msi\Lib\site-packages\pydiesel\api\handlers
copying build\lib\pydiesel\api\handlers\system_response_handler.py -> build\bdis
t.win-amd64\msi\Lib\site-packages\pydiesel\api\handlers
copying build\lib\pydiesel\api\handlers\__init__.py -> build\bdist.win-amd64\msi
\Lib\site-packages\pydiesel\api\handlers
copying build\lib\pydiesel\api\protobuf_pb2.py -> build\bdist.win-amd64\msi\Lib\
site-packages\pydiesel\api
creating build\bdist.win-amd64\msi\Lib\site-packages\pydiesel\api\transport
copying build\lib\pydiesel\api\transport\exceptions.py -> build\bdist.win-amd64\
msi\Lib\site-packages\pydiesel\api\transport
copying build\lib\pydiesel\api\transport\socket_transport.py -> build\bdist.win-
amd64\msi\Lib\site-packages\pydiesel\api\transport
copying build\lib\pydiesel\api\transport\transport.py -> build\bdist.win-amd64\m
si\Lib\site-packages\pydiesel\api\transport
copying build\lib\pydiesel\api\transport\__init__.py -> build\bdist.win-amd64\ms
i\Lib\site-packages\pydiesel\api\transport
copying build\lib\pydiesel\api\__init__.py -> build\bdist.win-amd64\msi\Lib\site
-packages\pydiesel\api
creating build\bdist.win-amd64\msi\Lib\site-packages\pydiesel\reflection
copying build\lib\pydiesel\reflection\exceptions.py -> build\bdist.win-amd64\msi
\Lib\site-packages\pydiesel\reflection
copying build\lib\pydiesel\reflection\reflector.py -> build\bdist.win-amd64\msi\
Lib\site-packages\pydiesel\reflection
creating build\bdist.win-amd64\msi\Lib\site-packages\pydiesel\reflection\types
copying build\lib\pydiesel\reflection\types\reflected_array.py -> build\bdist.wi
n-amd64\msi\Lib\site-packages\pydiesel\reflection\types
copying build\lib\pydiesel\reflection\types\reflected_binary.py -> build\bdist.w
in-amd64\msi\Lib\site-packages\pydiesel\reflection\types
copying build\lib\pydiesel\reflection\types\reflected_null.py -> build\bdist.win
-amd64\msi\Lib\site-packages\pydiesel\reflection\types
copying build\lib\pydiesel\reflection\types\reflected_object.py -> build\bdist.w
in-amd64\msi\Lib\site-packages\pydiesel\reflection\types
copying build\lib\pydiesel\reflection\types\reflected_primitive.py -> build\bdis
t.win-amd64\msi\Lib\site-packages\pydiesel\reflection\types
copying build\lib\pydiesel\reflection\types\reflected_string.py -> build\bdist.w
in-amd64\msi\Lib\site-packages\pydiesel\reflection\types
copying build\lib\pydiesel\reflection\types\reflected_type.py -> build\bdist.win
-amd64\msi\Lib\site-packages\pydiesel\reflection\types
copying build\lib\pydiesel\reflection\types\__init__.py -> build\bdist.win-amd64
\msi\Lib\site-packages\pydiesel\reflection\types
creating build\bdist.win-amd64\msi\Lib\site-packages\pydiesel\reflection\utils
copying build\lib\pydiesel\reflection\utils\class_builder.py -> build\bdist.win-
amd64\msi\Lib\site-packages\pydiesel\reflection\utils
copying build\lib\pydiesel\reflection\utils\class_loader.py -> build\bdist.win-a
md64\msi\Lib\site-packages\pydiesel\reflection\utils
copying build\lib\pydiesel\reflection\utils\__init__.py -> build\bdist.win-amd64
\msi\Lib\site-packages\pydiesel\reflection\utils
copying build\lib\pydiesel\reflection\__init__.py -> build\bdist.win-amd64\msi\L
ib\site-packages\pydiesel\reflection
copying build\lib\pydiesel\__init__.py -> build\bdist.win-amd64\msi\Lib\site-pac
kages\pydiesel
running install_egg_info
running egg_info
creating drozer.egg-info
writing requirements to drozer.egg-info\requires.txt
writing drozer.egg-info\PKG-INFO
writing top-level names to drozer.egg-info\top_level.txt
writing dependency_links to drozer.egg-info\dependency_links.txt
writing manifest file 'drozer.egg-info\SOURCES.txt'
reading manifest file 'drozer.egg-info\SOURCES.txt'
writing manifest file 'drozer.egg-info\SOURCES.txt'
Copying drozer.egg-info to build\bdist.win-amd64\msi\Lib\site-packages\drozer-2.
4.3_-py2.7.egg-info
running install_scripts
creating build\bdist.win-amd64\msi\Scripts
copying build\scripts-2.7\drozer -> build\bdist.win-amd64\msi\Scripts
copying build\scripts-2.7\drozer-complete -> build\bdist.win-amd64\msi\Scripts
copying build\scripts-2.7\drozer-repository -> build\bdist.win-amd64\msi\Scripts

copying build\scripts-2.7\drozer.bat -> build\bdist.win-amd64\msi\Scripts
creating dist
Traceback (most recent call last):
  File "setup.py", line 147, in <module>
    classifiers = [])
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\distutils\command\bdist_msi.py", line 236, in run
    sversion = "%d.%d.%d" % StrictVersion(version).version
  File "C:\Python27\lib\distutils\version.py", line 40, in __init__
    self.parse(vstring)
  File "C:\Python27\lib\distutils\version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '2.4.3-'

### Environment

**Operating system**:

Windows 7

**Java Version:**

JDK 1.7

**Android Version:**

**Drozer Version:** 
git cloned on 18/04/2018

**Install Method:** Built from source/.deb/.exe/..
Built from source .msi

### Drozer Config
```
Contents of ~/.drozer_config
```

### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
```

### ADB Logs
```
ADB Logs - To capture:
adb logcat -c
adb logcat > drozer_error.log
```

**Comment by Yogehi** [comment]
we have a docker image for drozer now

https://hub.docker.com/r/fsecurelabs/drozer

we recommend using that
