### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by 0xgaurang** [FSecureLABS/drozer#324]
On running drozer console connect, i am getting following error:
[Errno 2] No such file or directory

### Environment

**Operating system:** Mac OS High Sierra (Version 10.13.1)

**Java Version:** 1.7.0_80

**Drozer Version:** 2.4.4

**Install Method:** Installed using Python wheel.

Screenshot attached for reference.
<img width="458" alt="screen shot 2018-04-18 at 6 04 57 pm" src="https://user-images.githubusercontent.com/13043764/38932561-38c4cb30-4334-11e8-8b91-490340cf54ba.png">

**Comment by sheilajeck** [comment]
Same error with drozer v2.4.2 and 2.4.4. Any fixes for this issue?

**Comment by gaurang8492** [comment]
@amarekano @HenryHoggard Are you aware of any workaround for this on mac osx?

**Comment by pharazone** [comment]
same issue

**Comment by Yogehi** [comment]
we have a docker container now that should help with running drozer

https://hub.docker.com/r/fsecurelabs/drozer
