### ISSUE TITLE
Can't connect agent with console

### ISSUE THREAD

**Issue by ghost** [FSecureLABS/drozer#325]
### Steps to reproduce
1. I have install drozer agent on android emulator genymotion
2. I have install drozer console on my PC
3. I've tried to turn on agent on emulator, but it is impossibe

### Expected behaviour
Some times ago everything was OK. But something went wrong. I've already tried to reinstall everything -- it did not help.

### Actual behaviour
When I write `adb forward tcp:31415 tcp:31415` in console I see mistake.
````
adb server is out of date.  killing...
cannot bind 'tcp:5037': Address already in use
ADB server didn't ACK
* failed to start daemon *
error: 
error: 
````

### Environment

**Operating system**: Ubuntu

**Java Version:** openjdk version "1.8.0_162"

**Android Version:** 8.0

**Drozer Version:** 2.4.4

**Install Method:** Built from source/.deb/.exe/..

### Drozer Error Logs
```
drozer console connect --debug
There was a problem connecting to the drozer Server.

Things to check:

 - is the drozer Server running?
 - have you set up appropriate adb port forwards?
 - have you specified the correct hostname and port with --server?
 - is the server protected with SSL (add an --ssl switch)?
 - is the agent protected with a password (add a --password switch)?

Debug Information:
[Errno 111] Connection refused
```

### ADB Logs
```
adb logcat -c
adb server is out of date.  killing...
cannot bind 'tcp:5037': Address already in use
ADB server didn't ACK
* failed to start daemon *
- waiting for device -

```

**Comment by dgrivera** [comment]
Any update on this?

**Comment by QazNaz** [comment]
Solution:
Before running anything run these commands:
1) adb forward tcp:31415 tcp:31415
2) adb shell am startservice -n com.mwr.dz/.services.ServerService -c com.mwr.dz.START_EMBEDDED
3) drozer console connect
This should work

**Comment by Yogehi** [comment]
we have a docker container now that should help with running drozer

https://hub.docker.com/r/fsecurelabs/drozer

**Comment by Rocco-hash** [comment]
> we have a docker container now that should help with running drozer
> 
> https://hub.docker.com/r/fsecurelabs/drozer

I am running the docker container and everything looks good and have install the agent.apk on the android studio emulator and set up 
adb forward tcp:31415 tcp:31415 
but then then  go back to the docker container running drozer and run
 drozer console connect --server <phone IP address> 
I get this error
There was a problem connecting to the drozer Server.

Things to check:

 - is the drozer Server running?
 - have you set up appropriate adb port forwards?
 - have you specified the correct hostname and port with --server?
 - is the server protected with SSL (add an --ssl switch)?
 - is the agent protected with a password (add a --password switch)?

Debug Information:
[Errno 111] Connection refused

I have tried the ssl switch and the device doesnt have a password, any help greatly appreciated

**Comment by Yogehi** [comment]
First, forward port 31415 to the phone via ADB:

`adb forward tcp:31415 tcp:31415`

Next, obtain a shell into the container while adding an address to the container's Hosts file:

`docker run -it --add-host host.docker.internal:host-gateway fsecurelabs/drozer`

Finally, connect to drozer:

`drozer console connect --server host.docker.internal`

**Comment by Rocco-hash** [comment]
ok so I didnt have the sequence right before I start the container I run adb then spin up the container then connect with the command you gave, thank you soo much!

**Comment by AnshumanSingh1812** [comment]
I am trying to do the same thing as @Rocco-hash and I followed the steps exactly as mentioned above. I am still getting the same error. Does anyone know any other reason why it could be happening? Any help is highly appreciated.

**Comment by EvanFr** [comment]
> First, forward port 31415 to the phone via ADB:
> 
> `adb forward tcp:31415 tcp:31415`
> 
> Next, obtain a shell into the container while adding an address to the container's Hosts file:
> 
> `docker run -it --add-host host.docker.internal:host-gateway fsecurelabs/drozer`
> 
> Finally, connect to drozer:
> 
> `drozer console connect --server host.docker.internal`

I am following the exact steps with the correct order and it gives me:

There was a problem connecting to the drozer Server.

Things to check:

 - is the drozer Server running?
 - have you set up appropriate adb port forwards?
 - have you specified the correct hostname and port with --server?
 - is the server protected with SSL (add an --ssl switch)?
 - is the agent protected with a password (add a --password switch)?

Debug Information:
[Errno 111] Connection refused

What might be wrong?

**Comment by Yogehi** [comment]
Are you running Docker in a VM? Sometimes running stuff in a VM messes with your ability to forward stuff to a Docker container.

Besides that, make sure you have adb installed.

Besides that, idk

**Comment by EvanFr** [comment]
I am running a Docker
