### ISSUE TITLE
unsupported busybox - doesn't support PIE

### ISSUE THREAD

**Issue by lucasduffey** [FSecureLABS/drozer#327]
last released apk is v2.3.4 AFAIK.
* last release is 2.3.4 @ https://github.com/mwrlabs/drozer/releases
* last release is 2.3.4 @ https://labs.mwrinfosecurity.com/tools/drozer/
* last release is 2.3.1 @ https://github.com/mwrlabs/drozer-agent/releases

```
dz> run tools.setup.busybox
[-] This module is not supported on Android 5.0 and above yet. This is due to the enforcement of PIE binaries and will be updated in future versions of drozer.
```

**Comment by Yogehi** [comment]
yeah, other methods of installing updated busybox is the recommended method. stuff like magisk modules that also installs busybox.
