### ISSUE TITLE
Drozer does not find modules on windows 10 when installed from MSI

### ISSUE THREAD

**Issue by meetinthemiddle-be** [FSecureLABS/drozer#329]
### Steps to reproduce
1. Download MSI from the MWRLabs website
2. Run it in the directory where you want to have it installed
3. open Command Prompt and cd into in that directory
4. run drozer.bat without arguments
5. The output matches what the manual (*) states as "Congratulations! You are ready to connect drozer to a device, and start exploring."

(*) Manual found on https://labs.mwrinfosecurity.com/tools/drozer/ 

### Expected behaviour
When running the "drozer console" command, drozer/python should find the console module and run.

### Actual behaviour
When running the "drozer console" command, it errors out with "ImportError: No module named drozer.cli.console". If extra steps are necessary (PATH modifications, etc.) , this should be reflected in the manual.

### Environment

**Operating system**:
Windows 10

(Rest cut; this is a Python/Windows10 issue)

**Comment by jiangsi520** [comment]
I also met with this problem: I solved it with a low version (2.3.4).

**Comment by Greenwolf** [comment]
Still an issue, I also had to revert to 2.3.4.

**Comment by Yogehi** [comment]
we have a docker image for drozer now

https://hub.docker.com/r/fsecurelabs/drozer

we recommend using that
