### ISSUE TITLE
Connection was reset

### ISSUE THREAD

**Issue by nikhilgeo** [FSecureLABS/drozer#335]
Drozer console version: 2.4.4
Drozer agent apk version: 2.3.4
Device: Oneplus 6
I'm on Ubuntu 18.04

The console gets connected sucessuflly and I do get the console promt dz>. But if I run any drozer command for example list or run app.package.list -f sieve the the console just diconnects. When I check the apk in the Messages section it show "Connection was reset". 

Any idea how to resolve this ?

I ran the console in --debug mode but I couldn't see any logs from drozer in the logcat

**Comment by nikhilgeo** [comment]
```
java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
```

**Comment by Yogehi** [comment]
we have a docker container now that should help with running drozer

https://hub.docker.com/r/fsecurelabs/drozer
