### ISSUE TITLE
"global name 'java_path' is not defined" error on standard Kali setup

### ISSUE THREAD

**Issue by symmetrisch** [FSecureLABS/drozer#346]
### Steps to reproduce
1. Install drozer on recent Kali (`apt-get install drozer`)
2. Connect to device using regular instructions
3. Execute `run scanner.provider.traversal -a com.example.app`
4. Error message is `global name 'java_path' is not defined`

### Expected behaviour
The selected module should run without error.

### Actual behaviour
Module quits with an error message. I tried to fix this by setting `java_home` and `java_path` manually to `/usr/lib/jvm/java-8-openjdk-amd64` (?). But did not work.

### Environment

**Operating system**: 
`Linux kali 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-2kali1 (2019-05-15) x86_64 GNU/Linux`

**Java Version:**
`apt-get install drozer` installs `java-8-openjdk-amd64` by default 

**Android Version:**
7.1.2

**Drozer Version:** 
Agent: v2.3.4, Console: v2.4.4

**Install Method:**
`apt-get install drozer`

**Drozer Config:**
*empty*

**Comment by JBalanza** [comment]
Same issue here

**Comment by telahdihapus** [comment]
same issue, i stress out because deadline of my work, so i use santoku os, and problem was solved.

**Comment by pratheep704** [comment]
I had the same issue. We can overcome by doing the following steps:
1. Run sudo apt remove drozer
2. Download drozer deb pckg from https://github.com/mwrlabs/drozer/releases/download/2.4.4/drozer_2.4.4.deb
3. Run sudo dpkg -i drozer_2.4.4.deb

**Comment by Yogehi** [comment]
we have a docker image for drozer now

https://hub.docker.com/r/fsecurelabs/drozer

we recommend using that
