### ISSUE TITLE
Windows 10 error when building drozer

### ISSUE THREAD

**Issue by JustAsking1** [FSecureLABS/drozer#347]
### Steps to reproduce
1. Follow steps on installing drozer
2.Git clone works, cd drozer is no problem
3. run 'python.exe setup.py bdist_msi'

### Expected behaviour
MSI file should be created 

### Actual behaviour
Following traceback error invalid syntax:

Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    from src.drozer import meta
  File "C:\Users\admin\drozer\src\drozer\meta.py", line 63
    print "%s %s\n" % (name, version)
                  ^
SyntaxError: invalid syntax

### Environment

Windows 10:
```

**Comment by AnchitSharma** [comment]
use python 2.7 and if you have python 3+  just uninstall it.. and reinstall python 2.7

**Comment by Yogehi** [comment]
we have a docker image for drozer now

https://hub.docker.com/r/fsecurelabs/drozer

we recommend using that
