### ISSUE TITLE
Drozer windows error when running modules/packages "package not found" 

### ISSUE THREAD

**Issue by deepocean23** [FSecureLABS/drozer#348]
### Steps to reproduce
1. Installed Drozer using MSI file. 
2. Running Drozer using "Drozer console connect" command and its working and up.
3. Now trying to using command "run app.package.list" but getting error : [ unknown module: 'app.package.list' ]
4. Then tried to list the package using "LS" command but nothing found. 

### Expected behaviour
With "LS" command it should list the available modules of Drozer and using "run app.package.list" command it should list the package. 

### Actual behaviour
Instead of expected behavior, using "LS command" it is showing blank result. Using "run app.package.list" command it is showing this error : unknown module: 'app.package.list'
<img width="677" alt="drozer-error" src="https://user-images.githubusercontent.com/51744894/59582336-9bfdce80-90f5-11e9-8a7f-be967ec48b4e.PNG">

### Environment

**Operating system**:
Win 10 Prof

**Java Version:**
1.8

**Android Version:**
Emulator Android 7.0 API 24

**Drozer Version:** 
2.4.4

**Install Method:** Built from source/.deb/.exe/..
.msi

### Drozer Config
```
Contents of ~/.drozer_config
```

### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
```

### ADB Logs
```
ADB Logs - To capture:
adb logcat -c
adb logcat > drozer_error.log
```

**Comment by AnchitSharma** [comment]
i have the same issue but haven't find the perfect solution on internet

**Comment by DevilMayCrying** [comment]
bro,plz try to Enter the directory of drozer, and then connect to drozer
I had the same problem, and that solved it

**Comment by Yogehi** [comment]
we have a docker container now that should help with running drozer

https://hub.docker.com/r/fsecurelabs/drozer
