### ISSUE TITLE
drozer problem -java is not deifined

### ISSUE THREAD

**Issue by orijacov** [FSecureLABS/drozer#349]
hey i try to use the command 
" run scanner.provider.finduris -a com.mwr.example.sieve " 
and its give me an error. 

"exception in module: NameError: global name 'java_path' is not defined"

i try to delete and reinstall a few times .
I updated my kali linux up to date.
please help me.

**Comment by Yogehi** [comment]
we have a docker image for drozer now

https://hub.docker.com/r/fsecurelabs/drozer

we recommend using that
