### ISSUE TITLE
Unable to install drozer in Kali Linux

### ISSUE THREAD

**Issue by parteeksingh005** [FSecureLABS/drozer#350]
i have tried to install drozer with Building for Debian/Ubuntu/Mint and Installing .deb (Debian/Ubuntu/Mint) but both ways didn't worked for me. I am facing this issue while installing the drozer as below :
Error 1:
cd common; protoc --python_out=../src/pydiesel/api/ protobuf.proto
/bin/sh: 1: protoc: not found
make: *** [Makefile:55: src/pydiesel/api/protobuf_pb2.py] Error 127

Error 2:
dpkg: dependency problems prevent configuration of drozer:
 drozer depends on python-protobuf (>= 2.4.1); however:
  Package python-protobuf is not installed.

dpkg: error processing package drozer (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 drozer

i have installed protobuf also using pip command, but still getting this same issue.

**Comment by justin1846** [comment]
did you try:
pip install drozer-2.4.4-py2-none-any.whl
this worked for me on Kali release 2019.2

**Comment by adik69** [comment]
root@kali:# drozer console
Traceback (most recent call last):
  File "/usr/bin/drozer", line 30, in <module>
    __import__("drozer.cli.%s" % (sys.argv[1]))
  File "/usr/lib/python2.7/dist-packages/drozer/cli/console.py", line 8, in <module>
    from drozer.console import Console
  File "/usr/lib/python2.7/dist-packages/drozer/console/__init__.py", line 4, in <module>
    from drozer.console.console import Console
  File "/usr/lib/python2.7/dist-packages/drozer/console/console.py", line 5, in <module>
    from pydiesel.api.protobuf_pb2 import Message
  File "/usr/lib/python2.7/dist-packages/pydiesel/api/__init__.py", line 9, in <module>
    from pydiesel.api.frame import Frame
  File "/usr/lib/python2.7/dist-packages/pydiesel/api/frame.py", line 3, in <module>
    from pydiesel.api.protobuf_pb2 import Message
  File "/usr/lib/python2.7/dist-packages/pydiesel/api/protobuf_pb2.py", line 4, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named protobuf
root@kali:#  pip install drozer-2.4.4-py2-none-any.whl
WARNING: Requirement 'drozer-2.4.4-py2-none-any.whl' looks like a filename, but the file does not exist
ERROR: drozer-2.4.4-py2-none-any.whl is not a supported wheel on this platform.
root@kali:# 


Any suggestions what should be done here.

**Comment by KDR9666** [comment]
I'm facing the same issue, could you please anyone solve it.

┌─[kdr9666@parrot]─[~/Downloads]
└──╼ $sudo pip3 install drozer-2.4.4-py2-none-any.whl
ERROR: drozer-2.4.4-py2-none-any.whl is not a supported wheel on this platform.


Then I have tried with deb...

┌─[✗]─[kdr9666@parrot]─[~/Downloads]
└──╼ $sudo dpkg -i drozer_2.4.4.deb 
Selecting previously unselected package drozer.
(Reading database ... 555150 files and directories currently installed.)
Preparing to unpack drozer_2.4.4.deb ...
Unpacking drozer (2.4.4) ...
dpkg: dependency problems prevent configuration of drozer:
 drozer depends on python-protobuf (>= 2.4.1); however:
  Package python-protobuf is not installed.

dpkg: error processing package drozer (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 drozer

**Comment by omar1413** [comment]
i faced some problems to install it in kali but it work with me now .
i downloaded  drozer-2.4.4-py2-none-any.whl file form the realses in github then typed this command
sudo pip install drozer-2.4.4-py2-none-any.whl

make sure you installed all Prerequisites

**Comment by ivan-sincek** [comment]
Please see the solution at https://github.com/FSecureLABS/drozer/issues/375#issuecomment-652649354. I hope it will help. 😄

**Comment by ivan-sincek** [comment]
Please see if this is the solution for you https://github.com/FSecureLABS/drozer/issues/357#issuecomment-652669536. I hope it will help. 😄

**Comment by peek1** [comment]
doesnt for me as well in kali

**Comment by adv12rocks** [comment]
This issue can be solved by using python2.7 as current python version and using pip (uninstalling every other version of pip i.e. pip2 and pip3.

**Comment by Cy-Beard** [comment]
After hours of troubleshooting I have found a solution to this. I had the same issue having both python2.7 and python 3.8 installed, both pip and pip3 were symlinked to python3.8 pip. 
This was my solution:
sudo apt get install python2.7
cd /usr/lib/python2.7
sudo wget https://bootstrap.pypa.io/get-pip.py 
sudo python2.7 get-pip.py
which pip2.7
output -> /usr/local/bin/pip2.7

Now you can run:
sudo pip2.7 install drozer-2.4.4-py2-none-any.whl

**Comment by peek1** [comment]
thanks

**Comment by thevillagehacker** [comment]
# Drozer Installation in Kali 2021.1 Issue Solution

By default in kali 2021.1
```sh
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2021.1
Codename:	kali-rolling
```
The default python-pip is 2.7
All you have to do is to direct to `/usr/lib/python2.7/` and remove `get-pip.py`
Download new pip file from https://bootstrap.pypa.io/2.7/get-pip.py and run
```sh
sudo wget https://bootstrap.pypa.io/2.7/get-pip.py
sudo python2.7 get-pip.py
```
now check `which pip2.7`

## Error while installing drozer on pip
```sh
sudo pip2.7 install drozer-2.4.4-py2-none-any.whl
```
when you use the above command you will gwt error like below
```sh
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
WARNING: Requirement 'drozer-2.4.4-py2-none-any.whl' looks like a filename, but the file does not exist
Processing ./drozer-2.4.4-py2-none-any.whl
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/usr/lib/python2.7/drozer-2.4.4-py2-none-any.whl'
```
## Fix
- Direct to https://labs.f-secure.com/tools/drozer/
- Download [python.whl file](https://github.com/mwrlabs/drozer/releases/download/2.4.4/drozer-2.4.4-py2-none-any.whl)
### Run
```sh
sudo pip2.7 install drozer-2.4.4-py2-none-any.whl 
```
## Drozer will be Installed Successfully...

**Comment by thevillagehacker** [comment]
> i have tried to install drozer with Building for Debian/Ubuntu/Mint and Installing .deb (Debian/Ubuntu/Mint) but both ways didn't worked for me. I am facing this issue while installing the drozer as below :
> Error 1:
> cd common; protoc --python_out=../src/pydiesel/api/ protobuf.proto
> /bin/sh: 1: protoc: not found
> make: *** [Makefile:55: src/pydiesel/api/protobuf_pb2.py] Error 127
> 
> Error 2:
> dpkg: dependency problems prevent configuration of drozer:
> drozer depends on python-protobuf (>= 2.4.1); however:
> Package python-protobuf is not installed.
> 
> dpkg: error processing package drozer (--install):
> dependency problems - leaving unconfigured
> Errors were encountered while processing:
> drozer
> 
> i have installed protobuf also using pip command, but still getting this same issue.

Please check out this solution 
https://github.com/FSecureLABS/drozer/issues/350#issuecomment-785883801

**Comment by Yogehi** [comment]
we have a docker image for drozer now

https://hub.docker.com/r/fsecurelabs/drozer

we recommend using that

**Comment by Tink2Hack** [comment]
sudo docker pull fsecurelabs/drozer
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.29.1:53: read udp 192.168.29.133:58882->192.168.29.1:53: read: connection refused

Kali:~/Downloads$ sudo docker pull fsecurelabs/drozer latest
"docker pull" requires exactly 1 argument.

**Comment by Yogehi** [comment]
```
$ sudo docker pull fsecurelabs/drozer
Using default tag: latest
latest: Pulling from fsecurelabs/drozer
...
Status: Downloaded newer image for fsecurelabs/drozer:latest
docker.io/fsecurelabs/drozer:latest
```

based on the error message you get, it looks like your workstation is the issue. most likely DNS.

you can also build the docker container yourself: https://github.com/FSecureLABS/drozer/tree/develop/docker

**Comment by hugonh** [comment]
> ```shell
> install drozer-2.4.4-py2-none-any.whl
> ```


after that move the .whl file (` drozer-2.4.4-py2-none-any.whl` ) inside `/usr/bin/drozer/`
