### ISSUE TITLE
Error during install Drozer

### ISSUE THREAD

**Issue by alonf1983** [FSecureLABS/drozer#357]
Steps to reproduce

    git clone https://github.com/mwrlabs/drozer/
    cd drozer
    python setup.py bdist_wheel

Expected behaviour

should Building Python wheel

Actual behaviour:
root@kali:~/drozer# python setup.py bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 132, in <module>
    version = get_version(),
  File "setup.py", line 128, in get_version
    return subprocess.check_output(version_cmd).split('-', 1)[0]
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Environment

Operating system:Linux Kali

**Java Version:**1.7

Drozer Version: latest clone

please help

**Comment by ethicalhack3r** [comment]
Same error here on macOS

**Comment by theblackturtle** [comment]
Me too

**Comment by sadshade** [comment]
Yep, the same thing

**Comment by sadshade** [comment]
@alonf1983 change on 128 line in setup.py
`return subprocess.check_output(version_cmd).split('-', 1)[0]`
to
`return subprocess.check_output(version_cmd, shell=True).split('-', 1)[0]`

**Comment by abdilahrf** [comment]
FYI this still not implemented on the master branch

**Comment by ivan-sincek** [comment]
Please see the solution at https://github.com/FSecureLABS/drozer/issues/375#issuecomment-652649354. I hope it will help. 😄

**Comment by ivan-sincek** [comment]
Hi,

This is how I successfully installed `drozer` on `Kali 2020.2 (Linux 5.6.0-kali2-amd64 x86_64)` from a wheel.

Please run the following in this exact order:

```
wget https://github.com/FSecureLABS/drozer/releases/download/2.4.4/drozer-2.4.4-py2-none-any.whl
apt-get --assume-yes install python-pip
pip2 install wheel
pip2 install pyyaml
pip2 install pyhamcrest
pip2 install protobuf 
pip2 install pyopenssl 
pip2 install twisted
pip2 install service_identity
pip2 install drozer-2.4.4-py2-none-any.whl
```

The key is to use `pip2`.

Next, download `drozer agent` from https://labs.f-secure.com/tools/drozer/.

Install the agent on your mobile device and turn the agent on.

Then, connect your mobile device to your Kali machine and run:

```
apt-get --assume-yes install adb
adb start-server
adb forward tcp:31415 tcp:31415
drozer console connect
```

You should see no errors now.

Please share the solution with others if it helps.

Best of luck,
Ivan.

**Comment by kuchhalvanshika** [comment]
> Hi,
> 
> This is how I successfully installed `drozer` on `Kali 2020.2 (Linux 5.6.0-kali2-amd64 x86_64)` from a wheel.
> 
> Please run the following in this exact order:
> 
> ```
> wget https://github.com/FSecureLABS/drozer/releases/download/2.4.4/drozer-2.4.4-py2-none-any.whl
> apt-get --assume-yes install python-pip
> pip2 install wheel
> pip2 install pyyaml
> pip2 install pyhamcrest
> pip2 install protobuf 
> pip2 install pyopenssl 
> pip2 install twisted
> pip2 install service_identity
> pip2 install drozer-2.4.4-py2-none-any.whl
> ```
> 
> The key is to use `pip2` with `Python 2.7.0`.
> 
> Next, download `drozer agent` from https://labs.f-secure.com/tools/drozer/.
> 
> Install the agent on your mobile device and turn the agent on.
> 
> Then, connect your mobile device to your Kali machine and run:
> 
> ```
> apt-get --assume-yes install adb
> adb start-server
> adb forward tcp:31415 tcp:31415
> drozer console connect
> ```
> 
> You should see no errors now.
> 
> Please share the solution with others if it helps.
> 
> If for some strange reason you need `java` or `javac` run the following:
> 
> ```
> apt-get install --assume-yes openjdk-8-jdk-headless
> ```
> 
> Best of luck,
> Ivan.

Hi

After successfully installing all the libraries mentioned, still getting "-bash: drozer: command not found."

Environment - macOS Mojave
Java - 1.8

**Comment by ivan-sincek** [comment]
> > Hi,
> > This is how I successfully installed `drozer` on `Kali 2020.2 (Linux 5.6.0-kali2-amd64 x86_64)` from a wheel.
> > Please run the following in this exact order:
> > ```
> > wget https://github.com/FSecureLABS/drozer/releases/download/2.4.4/drozer-2.4.4-py2-none-any.whl
> > apt-get --assume-yes install python-pip
> > pip2 install wheel
> > pip2 install pyyaml
> > pip2 install pyhamcrest
> > pip2 install protobuf 
> > pip2 install pyopenssl 
> > pip2 install twisted
> > pip2 install service_identity
> > pip2 install drozer-2.4.4-py2-none-any.whl
> > ```
> > 
> > 
> > The key is to use `pip2` with `Python 2.7.0`.
> > Next, download `drozer agent` from https://labs.f-secure.com/tools/drozer/.
> > Install the agent on your mobile device and turn the agent on.
> > Then, connect your mobile device to your Kali machine and run:
> > ```
> > apt-get --assume-yes install adb
> > adb start-server
> > adb forward tcp:31415 tcp:31415
> > drozer console connect
> > ```
> > 
> > 
> > You should see no errors now.
> > Please share the solution with others if it helps.
> > If for some strange reason you need `java` or `javac` run the following:
> > ```
> > apt-get install --assume-yes openjdk-8-jdk-headless
> > ```
> > 
> > 
> > Best of luck,
> > Ivan.
> 
> Hi
> 
> After successfully installing all the libraries mentioned, still getting "-bash: drozer: command not found."
> 
> Environment - macOS Mojave
> Java - 1.8

Hi,

Unfortunately, I do not have access to macOS so I cannot test it... Maybe one day...

**Comment by lushann** [comment]
> > Hi,
> > This is how I successfully installed `drozer` on `Kali 2020.2 (Linux 5.6.0-kali2-amd64 x86_64)` from a wheel.
> > Please run the following in this exact order:
> > ```
> > wget https://github.com/FSecureLABS/drozer/releases/download/2.4.4/drozer-2.4.4-py2-none-any.whl
> > apt-get --assume-yes install python-pip
> > pip2 install wheel
> > pip2 install pyyaml
> > pip2 install pyhamcrest
> > pip2 install protobuf 
> > pip2 install pyopenssl 
> > pip2 install twisted
> > pip2 install service_identity
> > pip2 install drozer-2.4.4-py2-none-any.whl
> > ```
> > 
> > 
> > The key is to use `pip2` with `Python 2.7.0`.
> > Next, download `drozer agent` from https://labs.f-secure.com/tools/drozer/.
> > Install the agent on your mobile device and turn the agent on.
> > Then, connect your mobile device to your Kali machine and run:
> > ```
> > apt-get --assume-yes install adb
> > adb start-server
> > adb forward tcp:31415 tcp:31415
> > drozer console connect
> > ```
> > 
> > 
> > You should see no errors now.
> > Please share the solution with others if it helps.
> > If for some strange reason you need `java` or `javac` run the following:
> > ```
> > apt-get install --assume-yes openjdk-8-jdk-headless
> > ```
> > 
> > 
> > Best of luck,
> > Ivan.
> 
> Hi
> 
> After successfully installing all the libraries mentioned, still getting "-bash: drozer: command not found."
> 
> Environment - macOS Mojave
> Java - 1.8

![image](https://user-images.githubusercontent.com/24622986/100630787-efa1bd80-3365-11eb-927d-24598703fc88.png)
mac big sur

**Comment by ivan-sincek** [comment]
> > > Hi,
> > > This is how I successfully installed `drozer` on `Kali 2020.2 (Linux 5.6.0-kali2-amd64 x86_64)` from a wheel.
> > > Please run the following in this exact order:
> > > ```
> > > wget https://github.com/FSecureLABS/drozer/releases/download/2.4.4/drozer-2.4.4-py2-none-any.whl
> > > apt-get --assume-yes install python-pip
> > > pip2 install wheel
> > > pip2 install pyyaml
> > > pip2 install pyhamcrest
> > > pip2 install protobuf 
> > > pip2 install pyopenssl 
> > > pip2 install twisted
> > > pip2 install service_identity
> > > pip2 install drozer-2.4.4-py2-none-any.whl
> > > ```
> > > 
> > > 
> > > The key is to use `pip2` with `Python 2.7.0`.
> > > Next, download `drozer agent` from https://labs.f-secure.com/tools/drozer/.
> > > Install the agent on your mobile device and turn the agent on.
> > > Then, connect your mobile device to your Kali machine and run:
> > > ```
> > > apt-get --assume-yes install adb
> > > adb start-server
> > > adb forward tcp:31415 tcp:31415
> > > drozer console connect
> > > ```
> > > 
> > > 
> > > You should see no errors now.
> > > Please share the solution with others if it helps.
> > > If for some strange reason you need `java` or `javac` run the following:
> > > ```
> > > apt-get install --assume-yes openjdk-8-jdk-headless
> > > ```
> > > 
> > > 
> > > Best of luck,
> > > Ivan.
> > 
> > 
> > Hi
> > After successfully installing all the libraries mentioned, still getting "-bash: drozer: command not found."
> > Environment - macOS Mojave
> > Java - 1.8
> 
> ![image](https://user-images.githubusercontent.com/24622986/100630787-efa1bd80-3365-11eb-927d-24598703fc88.png)
> then ,add this path to $PATH.
> mac big sur

Can you try to run  `pip2 install service_identity`? Error message says "No module named service_identity".

If you get any other errors, just try to install what is missing.

**Comment by ivan-sincek** [comment]
> > > Hi,
> > > This is how I successfully installed `drozer` on `Kali 2020.2 (Linux 5.6.0-kali2-amd64 x86_64)` from a wheel.
> > > Please run the following in this exact order:
> > > ```
> > > wget https://github.com/FSecureLABS/drozer/releases/download/2.4.4/drozer-2.4.4-py2-none-any.whl
> > > apt-get --assume-yes install python-pip
> > > pip2 install wheel
> > > pip2 install pyyaml
> > > pip2 install pyhamcrest
> > > pip2 install protobuf 
> > > pip2 install pyopenssl 
> > > pip2 install twisted
> > > pip2 install service_identity
> > > pip2 install drozer-2.4.4-py2-none-any.whl
> > > ```
> > > 
> > > 
> > > The key is to use `pip2` with `Python 2.7.0`.
> > > Next, download `drozer agent` from https://labs.f-secure.com/tools/drozer/.
> > > Install the agent on your mobile device and turn the agent on.
> > > Then, connect your mobile device to your Kali machine and run:
> > > ```
> > > apt-get --assume-yes install adb
> > > adb start-server
> > > adb forward tcp:31415 tcp:31415
> > > drozer console connect
> > > ```
> > > 
> > > 
> > > You should see no errors now.
> > > Please share the solution with others if it helps.
> > > If for some strange reason you need `java` or `javac` run the following:
> > > ```
> > > apt-get install --assume-yes openjdk-8-jdk-headless
> > > ```
> > > 
> > > 
> > > Best of luck,
> > > Ivan.
> > 
> > 
> > Hi
> > After successfully installing all the libraries mentioned, still getting "-bash: drozer: command not found."
> > Environment - macOS Mojave
> > Java - 1.8
> 
> ![image](https://user-images.githubusercontent.com/24622986/100630787-efa1bd80-3365-11eb-927d-24598703fc88.png)
> then ,add this path to $PATH.
> mac big sur

Can you run once again  `pip2 install service_identity`? Error message says "No module named service_identity".

If you get any other errors, just try to install what is missing.

Can you check if you have all the required modules e.g. in `/usr/local/lib/python2.7/dist-packages/` (Kali Linux), but on macOS.
