### ISSUE TITLE
Drozer run app.package.list , but not list  my other   packages

### ISSUE THREAD

**Issue by blockchainguard** [FSecureLABS/drozer#359]
Drozer run app.package.list , but not list  my other   packages
==================
but just list  
dz> run  app.package.list
com.android.providers.telephony (绉诲姩缃戠粶閰嶇疆)
com.android.providers.calendar (鏃ュ巻瀛樺偍)
com.android.providers.media (濯掍綋瀛樺偍)
com.android.documentsui (鏂囨。)
com.android.gallery (鐩告満)
com.android.externalstorage (澶栭儴瀛樺偍璁惧)
com.android.htmlviewer (HTML 鏌ョ湅绋嬪簭)
com.android.mms.service (MmsService)
com.android.providers.downloads (涓嬭浇绠＄悊绋嬪簭)
com.android.browser (娴忚鍣?
[Errno 0] Error
dz>

**Comment by Yogehi** [comment]
try our docker image https://github.com/FSecureLABS/drozer/tree/develop/docker
