### ISSUE TITLE
Unexpected [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Antique811** [FSecureLABS/drozer#360]
### Steps to reproduce
1. pip install drozer
2. adb install drozer-agent-2.3.4.apk
3. run the app and click the button to Embedded Server
4. adb forward tcp:31415 tcp:31415
5. drozer console connect 

### Expected behaviour
connect to the drozer console

### Actual behaviour
drozer Console (v2.4.3)
[Errno 2] No such file or directory

### Environment

**Operating system**: MacOS 10.14.6

**Java Version:** 1.8.0_121

**Android Version:** 9.0

**Drozer Version:** 2.4.3

**Install Method:** pip install 

### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
sometime is [Errno:2] and sometime is [Error:35]  

Selecting 5bef03c5fa89fded (OnePlus ONEPLUS A6000 9)

            ..                    ..:.
           ..o..                  .r..
            ..a..  . ....... .  ..nd
              ro..idsnemesisand..pr
              .otectorandroidsneme.
           .,sisandprotectorandroids+.
         ..nemesisandprotectorandroidsn:.
        .emesisandprotectorandroidsnemes..
      ..isandp,..,rotectorandro,..,idsnem.
      .isisandp..rotectorandroid..snemisis.
      ,andprotectorandroidsnemisisandprotec.
     .torandroidsnemesisandprotectorandroid.
     .snemisisandprotectorandroidsnemesisan:
     .dprotectorandroidsnemesisandprotector.

drozer Console (v2.4.3)
[Errno 2] No such file or directory

or 

Selecting 5bef03c5fa89fded (OnePlus ONEPLUS A6000 9)

            ..                    ..:.
           ..o..                  .r..
            ..a..  . ....... .  ..nd
              ro..idsnemesisand..pr
              .otectorandroidsneme.
           .,sisandprotectorandroids+.
         ..nemesisandprotectorandroidsn:.
        .emesisandprotectorandroidsnemes..
      ..isandp,..,rotectorandro,..,idsnem.
      .isisandp..rotectorandroid..snemisis.
      ,andprotectorandroidsnemisisandprotec.
     .torandroidsnemesisandprotectorandroid.
     .snemisisandprotectorandroidsnemesisan:
     .dprotectorandroidsnemesisandprotector.

drozer Console (v2.4.3 debug mode)
[Errno 35] Resource temporarily unavailable
```
### PS
I have the same environment except the Operation System run in Windows 10,(same Java same Python Environmetn , py27 & jdk8)
and it runs well. 
so it's confused me very well.
and
in mac , it runs well for months , and just throw this expection about 3 days ago

**Comment by fujiokayu** [comment]
I wish [this issue tracker](#303) will help you.

**Comment by coffeehb** [comment]
I also meet this issue. But, i solved it. with this method.
rm ~/.drozer_history
and, restart  drozer. 
drozer console connect

**Comment by yannaingtun** [comment]
Thanks  @coffeehb 

Your method solved my issue.

**Comment by Yogehi** [comment]
try our docker image as well https://github.com/FSecureLABS/drozer/tree/develop/docker

**Comment by coffeehb** [comment]
> try our docker image as well https://github.com/FSecureLABS/drozer/tree/develop/docker

very nice
