### ISSUE TITLE
[Errno 1] Operation not permitted after command drozer console connect 

### ISSUE THREAD

**Issue by briglewis** [FSecureLABS/drozer#371]
### Steps to reproduce
1. Installed all dependencies
2. Worked initially but said I need to install service_update package (can't remember the name exactly) so did.
 3. I get the operation not permitted error after relaunching 

### Environment
OSX - VirtualEnv - Py2.7

**Java Version:**
java version "1.8.0_221"
**Android Version:**
Google Nexus 5
**Drozer Version:** 
drozer Console (v2.4.4)
**Install Method:** Built from source/.deb/.exe/..
pip install drozer-2.4.4-py2-none-any.whl
 
Thanks for your help! 

P.S I did read the other issues of the same name but saw one wasn't responded to and the other person re-installed python? I literally just installed python2.7 so it *should* be alright.

Cheers

Here's the error:
>> drozer console connect
![Screen Shot 2020-03-29 at 8 23 06 pm](https://user-images.githubusercontent.com/19641210/77845559-84628300-71fb-11ea-90c3-7e5977f25f70.png)

**Comment by jim-at-jibba** [comment]
Having same issue. Any luck?

**Comment by aasyria** [comment]
same is here also

**Comment by Yogehi** [comment]
we have a new docker image. have you tried that? https://github.com/FSecureLABS/drozer/tree/develop/docker

**Comment by pstoeckle** [comment]
@Yogehi The changes in https://github.com/FSecureLABS/drozer/pull/392 solved the problem for me.
