### ISSUE TITLE
/bin/sh: 1: protoc: not found make: *** [Makefile:55: src/pydiesel/api/protobuf_pb2.py] Error 127

### ISSUE THREAD

**Issue by KDR9666** [FSecureLABS/drozer#374]
### Steps to reproduce
1.git clone https://github.com/mwrlabs/drozer/
2.cd drozer/
3.make deb

### Expected behaviour
Tell us what should happen.

### Actual behaviour
┌─[kdr9666@parrot]─[~/drozer]
└──╼ $make deb
git submodule init && git submodule update
Submodule 'common' (https://github.com/mwrlabs/mercury-common.git) registered for path 'common'
Cloning into '/home/kdr9666/drozer/common'...
Submodule path 'common': checked out '48e81d5ae65ec38dbe1e4bfe09548203dcf13384'
cd common; protoc --python_out=../src/pydiesel/api/ protobuf.proto
/bin/sh: 1: protoc: not found
make: *** [Makefile:55: src/pydiesel/api/protobuf_pb2.py] Error 127

### Environment

**Operating system**: Parrot Linux (deb)

**Java Version:**
┌─[✗]─[kdr9666@parrot]─[~]
└──╼ $java -version
openjdk version "11.0.7-ea" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7-ea+9-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.7-ea+9-post-Debian-1, mixed mode, sharing)

**Android Version:**

**Drozer Version:** 

**Install Method:** Built from source/.deb/.exe/..

git clone https://github.com/mwrlabs/drozer/
cd drozer/
make deb

**Comment by jdonsec** [comment]
I have gotten the same error today, unable to install at the moment.

**Comment by Anand9893** [comment]
I am facing the same error when trying to install using the command 'make deb'

**Comment by BinhMinhptit** [comment]
same here

**Comment by syedumerqadri** [comment]
same

**Comment by 0xVIC** [comment]
Drozer is abandoned. Docker not work, python2 is obsolete now.

**Comment by Yogehi** [comment]
have you tried the new docker image? https://github.com/FSecureLABS/drozer/tree/develop/docker
