### ISSUE TITLE
Drozer installation error message - No module named drozer.cli.server

### ISSUE THREAD

**Issue by sundaramRNT** [FSecureLABS/drozer#375]
### Steps to reproduce
1. when tried to execute drozer console from the directory C:\drozer-develop\bin>

Error message 

C:\drozer-develop\bin>drozer server Traceback (most recent call last):   File "C:\drozer-develop\bin\drozer", line 30, in <module>     __import__("drozer.cli.%s" % (sys.argv[1])) ImportError: No module named drozer.cli.server

Windows 10 VM
Python 2.7 installed.
Environment variable set for Python and Java

**Comment by ivan-sincek** [comment]
Hi,

This is how I successfully installed `drozer` on `Kali 2020.2 (Linux 5.6.0-kali2-amd64 x86_64)` from a wheel.

Please run the following in the exact order:

```
wget https://github.com/FSecureLABS/drozer/releases/download/2.4.4/drozer-2.4.4-py2-none-any.whl
apt-get --assume-yes install python-pip
pip2 install wheel
pip2 install pyyaml
pip2 install pyhamcrest
pip2 install protobuf 
pip2 install pyopenssl 
pip2 install twisted
pip2 install service_identity
pip2 install drozer-2.4.4-py2-none-any.whl
```

The key is to use `pip2`.

Next, download `drozer agent` from https://labs.f-secure.com/tools/drozer/.

Install the agent on your mobile device and turn the agent on.

Then, connect your mobile device to your Kali machine and run:

```
apt-get --assume-yes install adb
adb start-server
adb forward tcp:31415 tcp:31415
drozer console connect
```

You should see no errors now.

Please share the solution with others if it helps.

Best of luck,
Ivan.

**Comment by ivan-sincek** [comment]
Please see if this is the solution for you https://github.com/FSecureLABS/drozer/issues/357#issuecomment-652669536. Try to replicate it on Windows. I hope it will help. 😄

**Comment by gobiasinfosec** [comment]
you need to add your drozer python path to the PYTHONPATH variable

for me it was doing this in powershell:
$env:PYTHONPATH += ";C:\PythonX\Lib\site-packages"

**Comment by Yogehi** [comment]
we created a docker image that should help this issue

**Comment by Yogehi** [comment]
https://github.com/FSecureLABS/drozer/tree/develop/docker
