### ISSUE TITLE
drozer console connect error

### ISSUE THREAD

**Issue by ganesh2183** [FSecureLABS/drozer#378]
When tried to execute drozer console receive the below error message

C:\>drozer.bat console connect
Traceback (most recent call last):
  File "C:\drozer\bin\drozer", line 30, in <module>
    __import__("drozer.cli.%s" % (sys.argv[1]))
ImportError: No module named drozer.cli.console

Windows 10 VM
Python 2.7 installed
Javac 1.7.0_80
Java version 1.8.0_121
Android Studio 4.0

How to resolve this problem

**Comment by gobiasinfosec** [comment]
you need to add your drozer python path to the PYTHONPATH variable

for me it was doing this in powershell:
$env:PYTHONPATH += ";C:\PythonX\Lib\site-packages"

**Comment by Yogehi** [comment]
can also try our docker image https://github.com/FSecureLABS/drozer/tree/develop/docker
