### ISSUE TITLE
dz> run app.service.send com.mwr.example.sieve com.mwr.example.sieve.CryptoService --msg 1 5 3 Didn't find class "ServiceBinder" on path: DexPathList[[zip file "/data/user/0/com.mwr.dz/cache/d781ddba6e94325b7a27a0fb2b5fd813.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]] dz> 

### ISSUE THREAD

**Issue by tea9** [FSecureLABS/drozer#383]
### Steps to reproduce
1.sudo pip install drozer-2.4.4-py2-none-any.whl
2.
3.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

### Environment

**Operating system**:

**Java Version:**

java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
**Android Version:**

**Drozer Version:** 
2.4.4

**Install Method:** Built from source/.deb/.exe/..

### Drozer Config
```
Contents of ~/.drozer_config
```

### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
```

### ADB Logs
```
ADB Logs - To capture:
adb logcat -c
adb logcat > drozer_error.log
```

thist error

dz> run app.service.send com.mwr.example.sieve com.mwr.example.sieve.CryptoService --msg 1 5 3
Didn't find class "ServiceBinder" on path: DexPathList[[zip file "/data/user/0/com.mwr.dz/cache/d781ddba6e94325b7a27a0fb2b5fd813.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
dz> 

dz> run app.service.send com.example.srv com.example.srv.Service --msg 1 2 3 --extra float value 0.1324 --extra string test value
exception in module: ReflectionException: Didn't find class "ServiceBinder" on path: DexPathList[[zip file "/data/user/0/com.mwr.dz/cache/d781ddba6e94325b7a27a0fb2b5fd813.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
Traceback (most recent call last):
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/drozer/console/session.py", line 394, in do_run
    module.run(argv[1:])
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/drozer/modules/base.py", line 183, in run
    result = self.execute(arguments)
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/drozer/modules/app/service.py", line 155, in execute
    result = binder.send_message(arguments.msg, arguments.timeout)
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/drozer/modules/common/binding.py", line 66, in send_message
    binder = self.obtain_binder()
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/drozer/modules/common/binding.py", line 53, in obtain_binder
    ServiceBinder = self.context.loadClass("common/ServiceBinder.apk", "ServiceBinder")
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/drozer/modules/common/loader.py", line 30, in loadClass
    Module.cache_klass(".".join([source, klass]), loader.loadClass(klass))
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pydiesel/reflection/utils/class_loader.py", line 28, in loadClass
    return self.getClassLoader().loadClass(klass);
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pydiesel/reflection/types/reflected_object.py", line 62, in _invoker
    result = self._reflector.invoke(self, method_name, *map(lambda arg: ReflectedType.fromNative(arg, reflector=self._reflector), args), **kwargs)
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pydiesel/reflection/reflector.py", line 83, in invoke
    raise ReflectionException(response.reflection_response.errormessage)
ReflectionException: Didn't find class "ServiceBinder" on path: DexPathList[[zip file "/data/user/0/com.mwr.dz/cache/d781ddba6e94325b7a27a0fb2b5fd813.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

dz> run app.provider.read content://com.mwr.example.sieve.FileBackupProvider/etc/hosts
Didn't find class "ByteStreamReader" on path: DexPathList[[zip file "/data/user/0/com.mwr.dz/cache/d781ddba6e94325b7a27a0fb2b5fd813.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

**Comment by tea9** [comment]
dz> run app.provider.read content://com.mwr.example.sieve.FileBackupProvider/etc/hosts 
Didn't find class "ByteStreamReader" on path: DexPathList[[zip file "/data/user/0/com.mwr.dz/cache/d781ddba6e94325b7a27a0fb2b5fd813.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

**Comment by tea9** [comment]
Didn't find class "XmlAssetReader" on path: DexPathList[[zip file "/data/user/0/com.mwr.dz/cache/d781ddba6e94325b7a27a0fb2b5fd813.apk"],nativeLibraryDirectories=[/system/lib, /vendor/lib]]

**Comment by Yogehi** [comment]
try our docker image https://github.com/FSecureLABS/drozer/tree/develop/docker

**Comment by tea9** [comment]
> try our docker image https://github.com/FSecureLABS/drozer/tree/develop/docker

ok Thanks

**Comment by anwar-saqib** [comment]
Hi, How can I install this docker image?
I am facing the same issue.
Didn't find class "ByteStreamReader" on path: DexPathList[[zip file "/data/user/0/com.mwr.dz/cache/d781ddba6e94325b7a27a0fb2b5fd813.apk"],nativeLibraryDirectories=[/system/lib, /system_ext/lib]]

**Comment by Yogehi** [comment]
1) install docker https://docs.docker.com/get-docker/
2) `docker pull fsecurelabs/drozer`
