### ISSUE TITLE
[Issue]Can't install drozer with error OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by hieutrandn9889** [FSecureLABS/drozer#384]
### Steps to reproduce
1. git clone https://github.com/mwrlabs/drozer/
2. cd drozer
3. python2 setup.py bdist_wheel

### Expected behaviour
I can install that

### Actual behaviour
Display an error "OSError: [Errno 2] No such file or directory"

### Environment

**Operating system**:
Mac OS catalina

**Java Version:**
 java version "1.7.0_80"

**Android Version:**

**Drozer Version:** 
2.4.4

**Install Method:** Built from source/.deb/.exe/..

### Drozer Config
```
Contents of ~/.drozer_config
java = /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/bin/java
javac = /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/bin/javac

### Drozer Error Logs
```
  File "setup.py", line 132, in <module>
    version = get_version(),
  File "setup.py", line 128, in get_version
    return subprocess.check_output(version_cmd).split('-', 1)[0]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by gabyavra** [comment]
same here

**Comment by wangzery** [comment]
Try [this](https://github.com/FSecureLABS/drozer/issues/379) , it worked for me.

**Comment by Yogehi** [comment]
try also the docker image https://github.com/FSecureLABS/drozer/tree/develop/docker
