### ISSUE TITLE
can this project be added in GSOC 2021

### ISSUE THREAD

**Issue by 1UC1F3R616** [FSecureLABS/drozer#386]
- since u have stoped it's development then is it possible that you can suggest this project for GSOC 2021?
- last date to apply is 20th Feb 2021
- I can update the project to use Python3 and higher version of Java along with any other ideas

What are your thoughts ? @dbradberry @metall0id and others

**Comment by metall0id** [comment]
I left F-Secure/MWR years ago, so unfortunately I don't get a vote :)

**Comment by 1UC1F3R616** [comment]
> I left F-Secure/MWR years ago, so unfortunately I don't get a vote :)

can you please tag someone who is more appropriate for this?

**Comment by Yogehi** [comment]
didn't know about this til it was too late :/ sorry
